//package OTPVerification;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLEncoder;
//import java.util.Date;
import java.util.Scanner;

import javax.net.ssl.HttpsURLConnection;

public class SendSms {
	
	public static void sendSms(String message,String number)
	{
//		System.out.println(message);
//		System.out.println(number);
		try
		{
		
		String apiKey="zQLADsta5HyMFoWEigbZeTBl6Pxdk1rhSCnR2VumXfGN0qOUKw2KeS9Rvfkw05hZmidVqaXyTbjHMJBE";
		String sendId="FSTSMS";
		//important step...
		message=URLEncoder.encode(message, "UTF-8");
		String language="english";
		
		String route="p";
String myUrl="https://www.fast2sms.com/dev/bulk?authorization="+apiKey+"&sender_id="+sendId+"&message="+message+"&language="+language+"&route="+route+"&numbers="+number;
		
		//sending get request using java..
		
		URL url=new URL(myUrl);
		
		HttpsURLConnection con=(HttpsURLConnection)url.openConnection();
		
		
		con.setRequestMethod("GET");
		
		con.setRequestProperty("User-Agent", "Mozilla/5.0");
		con.setRequestProperty("cache-control", "no-cache");
		System.out.println("Wait..............");
		
		int code=con.getResponseCode();
		
		System.out.println("Response code : "+code);
		
		StringBuffer response=new StringBuffer();
		
		BufferedReader br=new BufferedReader(new InputStreamReader(con.getInputStream()));
		
		while(true)
		{
			String line=br.readLine();
			if(line==null)
			{
				break;
			}
			response.append(line);
		}
		
		System.out.println(response);
		
		
		}catch (Exception e) {
			// TODO: handle exception
			System.out.println(e);
			//e.printStackTrace();
		}
		
	}
	
	public  String generatingOTP(String number) {
		System.out.println("Program started.....");
		 OTP otp=new OTP();
		   String otpmessage=otp.generateOTP(5);
		   System.out.println( "Generate OTP : "+otpmessage);
		  
		//SendSms.sendSms("Enter this OTP generated by AARTI to  change your password  ..."+new Date().toLocaleString(), "6395585903");
		   SendSms.sendSms("Your OTP to recover your password of Techqui is "+otpmessage, number+" OTPs are SECRET. DO NOT disclose it to anyone.");
			return otpmessage;
	}
}